### PR TITLE
Filter data export new

### PR DESCRIPTION
**Pull request by rnugraha**
These are I think basically work of Gijs, Gustavo &  me

### CODE REVIEW

**Comment by cataphract** [comment]
What's the status of #3 given this?

**Comment by cataphract** [comment]
After a cursory glance, I found some serious flaws:
- Dependencies on core-db. This cannot be done, neither explicitly by having compile time dependencies (the obvious) case, neither by using duck typing and accessing internals nonetheless (for instance properties on the cells that are not declared in `AllDataProjection::getDataProperties()`). The first case is easy to find just by searching for imports including ".db".
- `HighDimExportService` contains SNP specific code! This is in addition to the implementation using core-db private parts.

**Comment by gijskant** [comment]
Dependencies removed from the exporters. In `HighDimExportService` there is one dependency left on core-db: for creating the disjunctive constraint.

**Comment by cataphract** [comment]
Why didn't you remove it as well?

**Comment by gijskant** [comment]
The `DisjunctionConstraintFactory` expects not a list of DataConstraints, but a Map from type to parameters, effectively limiting the disjunction to one constraint per type.
So... rewriting of `DisjunctionConstraintFactory` is required, but I cannot oversee the consequences just now.

**Comment by cataphract** [comment]
That's not true. From the JavaDocs:

```
    /**
     * A well-known constraint for building a disjunction of several
     * sub-constraints.
     *
     * Parameters: 'subconstraints' => <map with string key (the constraint
     *                                  name) and a map value (the parameters of
     *                                  the sub-constraint) or a list of maps
     *                                  value (for several constraints of the
     *                                  same type)>
     */
    public final static String DISJUNCTION_CONSTRAINT = 'disjunction'
```

you can give a list.

**Comment by cataphract** [comment]
I'm merging, we'll look at the remaining problems next week.

**Pull request merged**
