### PR TITLE
Add sex value to TFAM export.

### PR DESCRIPTION
**Pull request by gijskant**
Depends on branch issues/export-sex-value in
transmart-core-api.

### CODE REVIEW

**Comment by gijskant** [comment]
Fixes NAA-82.

**Comment by JanKanis** [comment]
NB: the corresponding branch in rest-api has failures

**Comment by JanKanis** [comment]
The (transmartApp) tests don't do anything with the sex value now, they probably should.

**Comment by JanKanis** [comment]
If the tests are updated I'm fine with this.

**Comment by gijskant** [comment]
Tests are updated.

**Comment by cataphract** [comment]
Related pull requests are:
https://github.com/thehyve/naa-transmart-core-api/pull/1
https://github.com/thehyve/naa-transmart-rest-api/pull/2

The rest-api one is still failing, even after I triggered a rebuild.

**Comment by gijskant** [comment]
That failure is related to https://github.com/thehyve/naa-transmart-core-db/pull/11 (order of SNP data cells). Perhaps merge that one first.

**Pull request merged**
